project:
  type: website
  output-dir: mysite
execute:
  freeze: auto 
website:
  title: "Test website with R language"
  navbar:
    left:
      - href: index.qmd
        text: main
      - href: about.qmd
        text: more
format:
  html:
    theme: cosmo
    css: styles.css
